### ISSUE TITLE
[NES] Mega Man & Rockman (Taiwan) clones

### ISSUE THREAD

**Issue by proper1g1r** [unexpectedpanda/retool-clonelists-metadata#71] opened 2024-04-05 05:23 UTC
I think the current clone list might be overlooking the Rockman games from Taiwan. Thanks to the last review in [my collection](https://archive.org/details/proper1g1r-collection), I just realized I have the following duplications that I think are not being covered right now:

- [Mega Man 2 (USA)](https://datomatic.no-intro.org/index.php?page=show_record&s=45&n=1398) & [Rockman 2 (Taiwan) (En) (Rockman 123)](https://datomatic.no-intro.org/index.php?page=show_record&s=45&n=6152)
- [Mega Man 3 (USA)](https://datomatic.no-intro.org/index.php?page=show_record&s=45&n=1401) & [Rockman III (Taiwan) (En) (Rockman 123)](https://datomatic.no-intro.org/index.php?page=show_record&s=45&n=6148)
- [Mega Man 4 (USA) (Rev 1)](https://datomatic.no-intro.org/index.php?page=show_record&s=45&n=1405) & [Rockman IV (Taiwan) (En) (Rockman 123)](https://datomatic.no-intro.org/index.php?page=show_record&s=45&n=6149)
- [Mega Man 5 (USA)](https://datomatic.no-intro.org/index.php?page=show_record&s=45&n=1407) & [Rockman V (Taiwan) (En) (Rockman 123)](https://datomatic.no-intro.org/index.php?page=show_record&s=45&n=6150)
- [Mega Man 6 (USA)](https://datomatic.no-intro.org/index.php?page=show_record&s=45&n=1408) & [Rockman VI (Taiwan) (En) (Rockman 123)](https://datomatic.no-intro.org/index.php?page=show_record&s=45&n=6151)

They all really seem to be the same game. I'm not sure how to fix that in the clone list, which is why I'm just filing the issue.

**Comment by unexpectedpanda** [comment] 2024-04-05 06:16
Thanks. This one's a dupe of [#320](https://github.com/unexpectedpanda/retool/issues/320). Basically the clone lists haven't been updated for a month, which is usually when people interested in the NES DAT file take notice.

I'll be able to make time soon, but I've been occupied with updating the application itself.

**Closed by unexpectedpanda** 2024-04-05 06:16 UTC
